baseURL = 'https://example.org/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = 'Aetheris'
theme = 'even'
hasCJKLanguage = true

[pagination]
  pagerSize = 5

[author]
  name = "Erybus"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 40
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 50

[params]
  version = "4.x"
  since = "2026"
  description = "探索科技与人文的融合，记录时代的思考与感悟"
  keywords = ["科技", "人文", "思考", "探索"]
  logoTitle = "Aetheris"
  archivePaginate = 50
  
  [params.author]
    name = "Erybus"
    bio = "热爱科技与人文的探索者，关注人工智能、金融市场和地缘政治，致力于记录时代的思考与感悟。"
    avatar = ""
  
  [params.social]
    a-email = "mailto:longlong.skyligo@gmail.com"
    g-github = "https://github.com/longlong-skyligo"
    
  [params.publicCDN]
    enable = true
